[build]
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
# These need to be set in Netlify's UI:
# RESEND_API_KEY - Your Resend API key
# CONTACT_EMAIL - Email address to receive contact form submissions (defaults to justin@dexintelligence.ca)
# NODE_ENV - Set to "production" for production builds